---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*"
- type: document
  path: index.md
  label: Index
upload_dir: imakethings
public_path: https://res.cloudinary.com/dey9hupke/image/upload/c_scale,w_auto:100,dpr_auto
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
