---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: index_title
  label: Index short title
  config:
    required: true
- type: text
  name: year
  label: year
  config:
    required: true
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: color
  type: color
  label: Color
  config:
    required: true
    color_format: Hex
- type: file
  name: image
  label: Image
- type: field_group_list
  name: side_images
  fields:
  - type: file
    name: url
    label: URL
  - type: text
    name: description
    label: Description
  label: Aside Images
pages:
- projects/04-connasseur.md
- projects/01-jim-cbasp.md
- projects/03-photo-booth.md
- projects/02-the-line.md
- projects/05-walter-live.md
